### ISSUE TITLE
Yomichan for English?

### ISSUE THREAD

**Issue by NeonGooRoo** [seth-js/yomichan-ru#2]
Hi, I am sorry for posting here, I don't know where else, you made amazing work and it really helped some of my friends.

Would you ever consider making a version of Yomichan for English? I have many Russian friends who want to learn English but there is nothing that works as well as yomichan. And I already have seen many posts looking for the same thing. I know that this is a huge request, but I know nothing in programming and it could help many people.

Sorry for bothering you, thanks for your amazing work anyway.

**Comment by SakiDailene** [comment]
> Hi, I am sorry for posting here, I don't know where else, you made amazing work and it really helped some of my friends.
> 
> Would you ever consider making a version of Yomichan for English? I have many Russian friends who want to learn English but there is nothing that works as well as yomichan. And I already have seen many posts looking for the same thing. I know that this is a huge request, but I know nothing in programming and it could help many people.
> 
> Sorry for bothering you, thanks for your amazing work anyway.


Hi @NeonGooRoo. Check out the latest chromium version of [Yomitan](https://chromewebstore.google.com/detail/yomitan-development-build/glnaenfapkkecknnmginabpmgkenenml).
It supports more than 20 languages including English.
You can also find en-en and en-ru dictionaries for Yomitan [here](https://github.com/themoeway/kaikki-to-yomitan/releases/tag/beta).

**Comment by NeonGooRoo** [comment]
Wow thank you!!!
